CREATE TABLE [dbo].[RM_Company]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID(),
	[InvCompanyId] INT NOT NULL,
	[InvCompanyName] NVARCHAR(200) NOT NULL,
	[InvNameAlias] NVARCHAR(20) NULL,
	[InvCurrency] NVARCHAR(3) NULL,
	[InvIndustry] NVARCHAR(255) NULL,
	[InvDomainId] INT NOT NULL DEFAULT -1,
	[RM_IsActive] BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_RM_Company PRIMARY KEY CLUSTERED ([Id])
)
