CREATE TABLE [dbo].[RM_DataItem]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
	[IndustryId] UNIQUEIDENTIFIER NULL,
	[KPITypeId] UNIQUEIDENTIFIER NOT NULL,
	[IsDebit] BIT NOT NULL,
	[IsAggregate] BIT NOT NULL,
	[Scale] INT NOT NULL,
	[ValueTypeId] UNIQUEIDENTIFIER NOT NULL,
	[CreatedBy] NVARCHAR(50) NULL,
	[CreatedOn] DATETIME2 NOT NULL DEFAULT ('0001-01-01T00:00:00.0000000'),
	[Description] NVARCHAR(300) NULL,
	[Name] NVARCHAR(150) NULL,
	[IsSystemDefined] BIT NOT NULL DEFAULT ((0)),
	[IsActive] BIT NOT NULL DEFAULT ((0)),
	CONSTRAINT [PK_RM_DataItem] PRIMARY KEY CLUSTERED ([Id]),
	CONSTRAINT [FK_RM_DataItem_RM_Industry_IndustryId] FOREIGN KEY ([IndustryId]) REFERENCES [dbo].[RM_Industry] ([Id]),
	CONSTRAINT [FK_RM_DataItem_RMX_KpiType_KPITypeId] FOREIGN KEY ([KPITypeId]) REFERENCES dbo.[RMX_KpiType] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_RM_DataItem_RMX_ValueType_ValueTypeId] FOREIGN KEY ([ValueTypeId]) REFERENCES dbo.[RMX_ValueType] ([Id]) ON DELETE CASCADE,
)
GO

CREATE NONCLUSTERED INDEX [IX_RM_DataItem_IndustryId] ON [dbo].[RM_DataItem] ([IndustryId])
GO
CREATE NONCLUSTERED INDEX [IX_RM_DataItem_KPITypeId] ON [dbo].[RM_DataItem] ([KPITypeId]) 
GO
CREATE NONCLUSTERED INDEX [IX_RM_DataItem_ValueTypeId] ON [dbo].[RM_DataItem] ([ValueTypeId]) 
GO
