CREATE TABLE [dbo].[RM_Industry]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID(),
	[InvIndustryId] INT NOT NULL,
	[InvIndustryName] NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_RM_Industry PRIMARY KEY CLUSTERED ([Id])
)
