CREATE TABLE [dbo].[RMX_WorkflowStatus]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
	[Name] NVARCHAR(50) NULL,
	CONSTRAINT PK_RMX_WorkflowStatus PRIMARY KEY CLUSTERED ([Id]) 
)
