CREATE TABLE [dbo].[RMX_KpiType]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
	[Name] NVARCHAR(50) NULL,
	[IsFinancial] BIT NOT NULL DEFAULT (0),
	[IsTemplate] BIT NOT NULL DEFAULT (0),
	CONSTRAINT PK_RMX_KpiType PRIMARY KEY CLUSTERED ([Id]) 
)
